import { Typography } from "@mui/material";
import { Form, Formik } from "formik";

import { useEffect, useState } from "react";
import * as Yup from "yup";
import {
  LoginTextField,
  SubmitButton,
} from "./components/common/Fields/AllFields";

import Cookies from "js-cookie";
import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import { useAuthReqSender } from "../hooks/postReq";

const Home: NextPage = () => {
  // take user info
  const userCookie: string | undefined = Cookies.get("user_information");
  const user = userCookie && JSON.parse(userCookie);

  useEffect(() => {
    if (user?.user_email) {
      // redirect to chat
      Router.push("/allProducts");
    }
  }, [user?.user_email]);

  const [processing, setProcessing] = useState<boolean>(false);
  // initial vlaue of form
  const initialValues = {
    user_email: "",
    user_password: "",
  };

  // validation schema using formik yup
  const validationSchema = Yup.object({
    user_email: Yup.string()
      .email("Invalid email format!")
      .required("Required!"),
    user_password: Yup.string().required("Required!"),
  });

  const { sendReq } = useAuthReqSender();

  // on submit function here
  const onSubmit = async (values: any, { resetForm }: { resetForm: any }) => {
    setProcessing((state: boolean) => !state);

    if (values) {
      sendReq({
        reqData: values,
        resetForm,
        setProcessing,
        endPoint: "authentication/auth",
      });
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          width: "100%",
          height: "95vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Formik
          initialValues={initialValues}
          validationSchema={validationSchema}
          onSubmit={onSubmit}
        >
          <Form
            style={{
              width: "50%",
              background: "#f1f1f1",
              padding: "30px",
            }}
          >
            <Typography
              sx={{
                fontSize: 25,
                fontWeight: 700,
                margin: "20px 0px",
                fontFamily: "Poppins",
              }}
            >
              Login
            </Typography>
            <LoginTextField
              type="text"
              name="user_email"
              label="Enter your email"
            />

            <LoginTextField
              type="password"
              name="user_password"
              label="Enter your password"
            />

            <SubmitButton processing={processing}>Login</SubmitButton>
          </Form>
        </Formik>
      </main>
    </div>
  );
};

export default Home;
